name: 'build-linux-factory'
description: 'Builds an image from a linux factory'
inputs:
  path:
    description: 'Root path of the linux factory'
    required: true
runs:
  using: 'composite'
  steps:
    # Modified from https://github.com/addnab/docker-run-action
  - name: Checkout 
    uses: actions/checkout@v3 # Required to mount the Github Workspace to a volume 

  - name: Attemt to list github workspace
    run: ls -R ${{github.workspace}}
    shell: bash

  - name: Attempt to list github workspace hard coded
    run: ls -R /home/runner/work
    shell: bash

  - uses: addnab/docker-run-action@v3
    with:
      shell: bash
      image: cnshing/build-linux-factory:v1
      options: --privileged -v ${{ github.workspace }}:/work
      run: |
        echo "work"
        ls -R /work
        /entrypoint.sh ${{ inputs.factory-dir }}