name: 'build-linux-factory'
description: 'Builds an image from a linux factory'
inputs:
  path:
    description: 'Path of the linux factory'
    required: true
runs:
  using: 'composite'
  steps:

  - name: Assign host UID and GIDs as variables
    shell: bash
    run: | 
      echo "UID=$( id -u $USER )" >> $GITHUB_ENV
      echo "GID=$( id -g $USER )" >> $GITHUB_ENV

  - uses: addnab/docker-run-action@v3
    with:
      shell: bash
      image: cnshing/build-linux-factory:v1
      # UID matching between host and container from https://stackoverflow.com/a/45640469
      options: >
        --privileged
        -u ${{ env.UID }}:${{ env.GID }}
        -v ${{ github.action_path }}/entrypoint.sh:/entrypoint.sh 
        -v ${{ github.workspace }}:/github_workspace 
        -e GITHUB_WORKSPACE=/github_workspace
      run: |
        chmod +x /entrypoint.sh
        /entrypoint.sh "${{ inputs.path }}"