name: 'build-linux-factory'
description: 'Builds an image from a linux factory'
inputs:
  path:
    description: 'Path of the linux factory'
    required: true
runs:
  using: 'composite'
  steps:
  - uses: addnab/docker-run-action@v3
    with:
      shell: bash
      image: cnshing/build-linux-factory:v1
      options: >
        --privileged
        -v ${{ github.action_path }}/entrypoint.sh:/entrypoint.sh 
        -v ${{ github.workspace }}:/github_workspace 
        -e GITHUB_WORKSPACE=/github_workspace
      run: |
        chmod +x /entrypoint.sh
        echo "List dirs before chmod"
        ls -lR /github_workspace
        sudo chmod -R a+rwx /github_workspace
        echo "After chmod"
        ls -lR /github_workspace
        sudo -E /entrypoint.sh "${{ inputs.path }}"