name: 'build-linux-factory'
description: 'Builds an image from a linux factory'
inputs:
  path:
    description: 'Path of the linux factory'
    required: true
runs:
  using: 'composite'
  steps:

  - name: Debug $GITHUB_WORKSPACE and ${{ github.workspace }}
    shell: bash
    run: | 
      echo $GITHUB_WORKSPACE
      echo ${{ github.workspace }}

  - uses: addnab/docker-run-action@v3
    with:
      shell: bash
      image: cnshing/build-linux-factory:v1
      # UID matching between host and container from https://stackoverflow.com/a/45640469
      options: >
        --privileged
        -u $( id -u $USER ):$( id -g $USER )
        -v ${{ github.action_path }}/entrypoint.sh:/entrypoint.sh 
        -v ${{ github.workspace }}:/github_workspace 
        -e GITHUB_WORKSPACE=/github_workspace
      run: |
        chmod +x /entrypoint.sh
        /entrypoint.sh "${{ inputs.path }}"