name: 'build-linux-factory'
description: 'Builds an image from a linux factory'
inputs:
  factory-dir:
    description: 'Root directory of the linux factory'
    required: true
runs:
  using: 'composite'
  # Modified from https://github.com/addnab/docker-run-action
- name: Checkout 
  uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 

- uses: addnab/docker-run-action@v3
  with:
    shell: bash
    image: cnshing/build-linux-factory:v1
    options: --privileged -v ${{ github.workspace }}:/work -e GITHUB_WORKSPACE=/work
    run: |
      /work/entrypoint.sh ${{ inputs.factory-dir }}