name: 'build-linux-factory'
description: 'Builds an image from a linux factory'
inputs:
  path:
    description: 'Path of the linux factory relative to $GITHUB_WORKSPACE.'
    required: false
runs:
  using: 'composite'
  steps:
  - uses: addnab/docker-run-action@v3
    with:
      shell: bash
      image: cnshing/build-linux-factory:v1
      options: >
        --privileged
        -v ${{ github.action_path }}/entrypoint.sh:/entrypoint.sh 
        -v ${{ github.workspace }}:/github_workspace 
        -e GITHUB_WORKSPACE=/github_workspace
        -e PYTHONUNBUFFERED=1
      run: |
        chmod +x /entrypoint.sh
        FACTORY_DIR="$GITHUB_WORKSPACE${{ inputs.path }}"
        cd $FACTORY_DIR
        sudo virtualenv env
        sudo make build

  - name: Setup upterm session
    uses: lhotari/action-upterm@v1
