name: 'build-linux-factory'
description: 'Builds an image from a linux factory'
inputs:
  path:
    description: 'Root path of the linux factory'
    required: true
runs:
  using: 'composite'
  steps:

  - uses: addnab/docker-run-action@v3
    with:
      shell: bash
      image: cnshing/build-linux-factory:v1
      options: --privileged -v ${{ github.action_path }}:/work
      run: |
        /github_workspace/entrypoint.sh ${{ inputs.path }}