run-name: Open a ssh session for debugging github actions

on:
  workflow_dispatch:
jobs:
  session:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTIONPATH = ${{ github.workspace }}/build-linux-factory
      GITHUB_WORKSPACE = ${{ github.workspace }}
    steps:
      # Steps to install GH CLI copied from https://github.com/cli/cli/blob/trunk/docs/install_linux.md
    - name: Install GH CLI
      run: |
        sudo mkdir -p -m 755 /etc/apt/keyrings && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null 
        sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg 
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null 
        sudo apt update 
        sudo apt install gh -y

    - name: Checkout build-linux-factory
    - uses: actions/checkout@v4
      with:
        path: build-linux-factory
        fetch-depth: 0

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
