run-name: Test action ver. @${{ inputs.branch }} on cnshing's debian live-cd basic build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Linux Factory target test branch"
        required: false
        default: "v2"
      checkout_ref:
        description: "cnshing/debian-livecd sha or ref to checkout"
        required: false
        default: "v0.2.0"
  workflow_call:
    inputs:
      branch:
        type: string
        description: "Linux Factory target test branch"
        required: false
        default: "v2"
      checkout_ref:
        type: string
        description: "cnshing/debian-livecd sha or ref to checkout"
        required: false
        default: "v0.2.0"

env:
  LB_CACHE: "true"
  LB_CACHE_STAGES: "bootstrap chroot"
  LB_CACHE_PACKAGES: "true"

jobs:
  build:
    runs-on: ubuntu-24.04 # This version should be compatiable with cnshing debian-livecd
    steps:

      - uses: actions/checkout@v6
        with:
          repository: 'cnshing/debian-livecd'
          ref: ${{ inputs.checkout_ref }}
          path: debian-livecd
          lfs: true

      - name: Force enable live-build cache
        run: |
          set -euo pipefail

          CONF="debian-livecd/lb/auto/config"

          sudo sed -i \
            -e 's/--cache "\${CACHE:-true}"/--cache "true"/' \
            -e '/--cache "true"/a\    --cache-stages "bootstrap chroot" \\' \
            -e '/--cache-stages "bootstrap chroot"/a\    --cache-packages "true" \\' \
            "$CONF"

          sudo mkdir -p /etc/live
          cat <<'EOF' | sudo tee /etc/live/build.conf > /dev/null
          LB_CACHE="true"
          LB_CACHE_STAGES="bootstrap chroot"
          LB_CACHE_PACKAGES="true"
          EOF

      - name: Build cnshing Minimum Debian Live-CD
        uses: jenseng/dynamic-uses@v1
        with:
          uses: cnshing/build-linux-factory@${{ inputs.branch }}
          with: |
            path: debian-livecd
  
      - uses: actions/upload-artifact@v4
        with:
          name: cnshing-iso
          path: ${{ github.workspace }}/debian-livecd/.build/lb/*.iso
      
