run-name: Test action ver. @${{ inputs.branch }} on clayrisser's linux factory

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Linux Factory target test branch"
        required: false
        default: "v2"
  push:
    branches: 
      - releases/v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v2
        with:
          remove-android: 'true'
          remove-codeql: 'true'

      - uses: actions/checkout@v5
        with:
          repository: 'clayrisser/linux-factory'
          path: linux-factory
          lfs: true

      - name: Cleanup and check broken example overlays
        run: | 
          rm -r $GITHUB_WORKSPACE/linux-factory/overlays/example
          ls $GITHUB_WORKSPACE/linux-factory/overlays

      - name: Build Linux Factory
        uses: jenseng/dynamic-uses@v1
        with:
          uses: cnshing/build-linux-factory@${{ inputs.branch }}
          with: |
            path: linux-factory
  
      - uses: actions/upload-artifact@v4
        with:
          name: clayrisser-iso
          path: ${{ github.workspace }}/linux-factory/.build/lb/*.iso
      
